Alt+b script-binding bookmarks/bookmark-add
Alt+n script-binding bookmarks/bookmark-add-named
Alt+l script-binding bookmarks/bookmark-browse
Alt+. script-binding bookmarks/bookmark-next
Alt+, script-binding bookmarks/bookmark-prev
Alt+d script-binding bookmarks/bookmark-delete
